### PR TITLE
Support RV32E

### PR DESCRIPTION
**Pull request by kito-cheng**

### CODE REVIEW

**Comment by kito-cheng** [comment]
Rebase due to it's seem sneak in some other commits.

**Comment by kito-cheng** [comment]
@palmer-dabbelt binutils part not merge yet, could you take a look? thanks :)

**Comment by palmer-dabbelt** [comment]
Ugh, we've rebased too many times.  Is this the only patch?  https://github.com/riscv/riscv-binutils-gdb/pull/87/commits/ecea283b4e52e54ff9e0f0db8d1955837510323c

**Comment by kito-cheng** [comment]
wait a minute, let me rebase it

**Comment by kito-cheng** [comment]
holy shit, it got stuck when writing to github...and yes, https://github.com/riscv/riscv-binutils-gdb/commit/ecea283b4e52e54ff9e0f0db8d1955837510323c is the only patch.
```
Counting objects: 5374, done.
Delta compression using up to 24 threads.
Compressing objects: 100% (1304/1304), done.
Writing objects:  34% (1828/5374)  
```

**Comment by kito-cheng** [comment]
holy shit, it got stuck when writing to github...and yes, https://github.com/riscv/riscv-binutils-gdb/commit/ecea283b4e52e54ff9e0f0db8d1955837510323c is the only patch.
```
Counting objects: 5374, done.
Delta compression using up to 24 threads.
Compressing objects: 100% (1304/1304), done.
Writing objects:  34% (1828/5374)  
```

**Pull request closed without merging**
