### PR TITLE
lw (a0) doesn't compress

### PR DESCRIPTION
**Pull request by palmer-dabbelt**
Don't merge this, as it's just a test case.  This is a low-priority bug, I'm just opening the PR so we don't forget about it.

### CODE REVIEW

**Comment by aswaterman** [comment]
We should generalize the test to make sure the following all compress (since they use different patterns):

sw a0, (a0)
lw a0, (sp)
sw a0, (sp)

**Comment by aswaterman** [comment]
I pushed a commit to this PR that fixes the bug.

**Comment by jim-wilson** [comment]
I expanded the tests to include every case, and checked the patches into the FSF binutils tree.

**Comment by jim-wilson** [comment]
Do I need to backport this patch, and if so, how exactly do I do that?

**Comment by palmer-dabbelt** [comment]
I already did.  You can backport patches via

````
git checkout riscv-binutils-2.29
git cherry-pick HASH
````

you'll probably want git-merge-changelog, as otherwise you'll get a lot of conflicts.  I'm closing the PR, as it's fixed.

**Pull request closed without merging**
