### PR TITLE
bfd: RISC-V: relax to gp in more cases.

### PR DESCRIPTION
**Pull request by aswaterman**
bfd/ChangeLog:

2017-02-21  Andrew Waterman  <andrew@sifive.com>

	Relax to gp in more cases.
	* elfnn-riscv.c (GP_NAME): New macro.
	(riscv_global_pointer_value): Use it.
	(_bfd_riscv_relax_lui): If symbol and global pointer are in same
	output section, consider only that section's alignment.

### CODE REVIEW

**Comment by aswaterman** [comment]
@kito-cheng

**Comment by kito-cheng** [comment]
@kuanlinchentw say look good to him :)

**Comment by aswaterman** [comment]
cool, palmer submitted patch

**Comment by palmer-dabbelt** [comment]
Upstream.

**Pull request closed without merging**
