### PR TITLE
Error, don't warn, for shfit amounts/CSRs

### PR DESCRIPTION
**Pull request by aswaterman**

### CODE REVIEW

**Comment by aswaterman** [comment]
#77

**Comment by aswaterman** [comment]
@palmer-dabbelt if this is the right thing to do, can you go ahead and merge it?  My internet access is spotty.

**Comment by riscCoder** [comment]
By deleting the 'shift-warn' branch this should halt on error?

**Comment by palmer-dabbelt** [comment]
Well, merging the PR is what really does it.  We just delete the branch after merging so there aren't a lot of branches floating around.

**Pull request merged**
